<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Product Invoice</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #333;
            margin: 0;
            padding: 0;
        }
        .invoice-container {
            width: 95%;
            margin: 20px auto;
            border: 1px solid #ddd;
            padding: 20px 30px;
            border-radius: 8px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #222;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h2 {
            margin: 0;
            font-size: 22px;
        }
        .info-section {
            margin-bottom: 20px;
            display: flex;
            justify-content: space-between;
        }
        .info-box {
            width: 48%;
        }
        .info-box h4 {
            margin-bottom: 6px;
            color: #222;
            border-bottom: 1px solid #ddd;
            padding-bottom: 4px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            font-size: 13px;
        }
        th, td {
            border: 1px solid #999;
            padding: 8px;
            text-align: center;
        }
        th {
            background-color: #f2f2f2;
        }
        tfoot td {
            font-weight: bold;
        }
        .footer {
            text-align: center;
            margin-top: 25px;
            font-size: 12px;
            color: #555;
        }
    </style>
</head>
<body>

<div class="invoice-container">

    <div class="header">
        <h2>Product Invoice</h2>
        <small>Date: <?php echo date('d M Y, h:i A'); ?></small>
    </div>

    <?php if (!empty($soldproduct)) { 
        $customer = $soldproduct[0]; // Common customer info
    ?>
    <div class="info-section">
        <div class="info-box">
            <h4>Customer Details</h4>
            <p><strong>Name:</strong> <?php echo strtoupper($customer->name); ?></p>
            <p><strong>Phone:</strong> <?php echo $customer->phone; ?></p>
            <p><strong>Distributor Code:</strong> <?php echo $customer->distributorCode; ?></p>
            <p><strong>Registered On:</strong> <?php echo date('d-m-Y', strtotime($customer->customerCreatedAt)); ?></p>
        </div>
        <div class="info-box" style="text-align:right;">
            <h4>Generated By</h4>
            <p><strong>Invoice ID:</strong> INV<?php echo date('ymdHis', strtotime($customer->customerCreatedAt)); ?></p>
            <p><strong>Generated On:</strong> <?php echo date('d-m-Y H:i A'); ?></p>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>SL No.</th>
                <th>Product Name</th>
                <th>Quantity</th>
                <th>DP Price</th>
                <th>MRP</th>
                <th>Total (DP)</th>
                <th>Total (MRP)</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            $count = 1; 
            $total_dp = 0;
            $total_mrp = 0;
            foreach($soldproduct as $item){ 
                $total_dp += $item->total_dp_price;
                $total_mrp += $item->total_mrp_price;
            ?>
            <tr>
                <td><?php echo $count++; ?></td>
                <td><?php echo $item->productName; ?></td>
                <td><?php echo $item->quantity; ?></td>
                <td><?php echo number_format($item->total_dp_price / $item->quantity, 2); ?></td>
                <td><?php echo number_format($item->total_mrp_price / $item->quantity, 2); ?></td>
                <td><?php echo number_format($item->total_dp_price, 2); ?></td>
                <td><?php echo number_format($item->total_mrp_price, 2); ?></td>
            </tr>
            <?php } ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5" style="text-align:right;">Grand Total (DP)</td>
                <td><?php echo number_format($total_dp, 2); ?></td>
                <td><?php echo number_format($total_mrp, 2); ?></td>
            </tr>
        </tfoot>
    </table>
    <?php } else { ?>
        <p style="text-align:center;color:red;">No sold product data available.</p>
    <?php } ?>

    <div class="footer">
        <p>Thank you for your purchase!</p>
        <p><em>This is a computer-generated invoice and does not require a signature.</em></p>
    </div>

</div>

</body>
</html>
